##### Index   -    Il servira plus tard pour avoir juste une barre de recherche.
ign_info_git_index:
    path:     /index
    defaults: { _controller: IGNInfoGitBundle:Begining:index }


##### Begining
ign_info_git_homepage:
    path:     /
    defaults: { _controller: IGNInfoGitBundle:Begining:home }

ign_info_git_tree:
    path:     /tree
    defaults: { _controller: IGNInfoGitBundle:Begining:tree }


##### Branches
ign_info_git_all_branches:
    path:     /branches/
    defaults: { _controller: IGNInfoGitBundle:Branches:allbranches }

ign_info_git_a_branch:
    path:     /branch/{name}
    defaults: { _controller: IGNInfoGitBundle:Branches:abranch }

ign_info_git_a_contributor_with_a_branch:
    path:     /contributor/{contributor}/{branch}
    defaults: { _controller: IGNInfoGitBundle:Branches:acontributorwithbranch }


##### Contributors
ign_info_git_all_contributors:
    path:     /contributors
    defaults: { _controller: IGNInfoGitBundle:Contributors:allcontributors }

ign_info_git_a_contributor:
    path:     /contributor/{name}
    defaults: { _controller: IGNInfoGitBundle:Contributors:acontributor }

##### Files tree
ign_info_git_files_tree:
    path:     /files/
    defaults: { _controller: IGNInfoGitBundle:Files:tree }
